Homework 1
================
Sanjana Batabyal

This is my solution to Homework 1.

``` r
library(tidyverse)
```

    ## ── Attaching packages ───────────────────────────────────────────────────── tidyverse 1.3.0 ──

    ## ✓ ggplot2 3.3.2     ✓ purrr   0.3.4
    ## ✓ tibble  3.0.3     ✓ dplyr   1.0.2
    ## ✓ tidyr   1.1.2     ✓ stringr 1.4.0
    ## ✓ readr   1.3.1     ✓ forcats 0.5.0

    ## ── Conflicts ──────────────────────────────────────────────────────── tidyverse_conflicts() ──
    ## x dplyr::filter() masks stats::filter()
    ## x dplyr::lag()    masks stats::lag()

## Problem 1

Create a data frame comprised of the specified elements

``` r
prob1df =
  tibble(
      samp = rnorm(10),
      samp_gt_0 = samp > 0,
      char_vec = c("a", "b", "c", "d", "e", "f", "g", "h", "i", "j"),
      factor_vec = factor(c("low", "low", "low", "mod", "mod", "mod", "mod","high", "high", "high"))
)
```

Take the mean of each variable in my data frame

``` r
mean(pull(prob1df, samp))
```

    ## [1] -0.1712435

``` r
mean(pull(prob1df, samp_gt_0))
```

    ## [1] 0.4

``` r
mean(pull(prob1df, char_vec))
```

    ## Warning in mean.default(pull(prob1df, char_vec)): argument is not numeric or
    ## logical: returning NA

    ## [1] NA

``` r
mean(pull(prob1df, factor_vec))
```

    ## Warning in mean.default(pull(prob1df, factor_vec)): argument is not numeric or
    ## logical: returning NA

    ## [1] NA

The mean for my sample is 0.1026824 and the mean for my sample greater
than zero is 0.6 but I could not get the mean for a character vector or
the factor vector.

``` r
as.numeric(pull(prob1df, samp))
```

    ##  [1] -0.7147221 -0.1343467  0.9198547 -0.4216511 -0.2967586  0.3335384
    ##  [7]  0.5900533  0.4051230 -1.5685207 -0.8250049

``` r
as.numeric(pull(prob1df, samp_gt_0))
```

    ##  [1] 0 0 1 0 0 1 1 1 0 0

``` r
as.numeric(pull(prob1df, char_vec))
```

    ## Warning: NAs introduced by coercion

    ##  [1] NA NA NA NA NA NA NA NA NA NA

``` r
as.numeric(pull(prob1df, factor_vec))
```

    ##  [1] 2 2 2 3 3 3 3 1 1 1

## Problem 2

``` r
data("penguins", package = "palmerpenguins")
summary(penguins)
```

    ##       species          island    bill_length_mm  bill_depth_mm  
    ##  Adelie   :152   Biscoe   :168   Min.   :32.10   Min.   :13.10  
    ##  Chinstrap: 68   Dream    :124   1st Qu.:39.23   1st Qu.:15.60  
    ##  Gentoo   :124   Torgersen: 52   Median :44.45   Median :17.30  
    ##                                  Mean   :43.92   Mean   :17.15  
    ##                                  3rd Qu.:48.50   3rd Qu.:18.70  
    ##                                  Max.   :59.60   Max.   :21.50  
    ##                                  NA's   :2       NA's   :2      
    ##  flipper_length_mm  body_mass_g       sex           year     
    ##  Min.   :172.0     Min.   :2700   female:165   Min.   :2007  
    ##  1st Qu.:190.0     1st Qu.:3550   male  :168   1st Qu.:2007  
    ##  Median :197.0     Median :4050   NA's  : 11   Median :2008  
    ##  Mean   :200.9     Mean   :4202                Mean   :2008  
    ##  3rd Qu.:213.0     3rd Qu.:4750                3rd Qu.:2009  
    ##  Max.   :231.0     Max.   :6300                Max.   :2009  
    ##  NA's   :2         NA's   :2

``` r
ncol(penguins)
```

    ## [1] 8

``` r
nrow(penguins)
```

    ## [1] 344

The data are describing information about different types of penguins
and have categorized the penguins by different species types (there are
3) and different locations (they hail from 3 different islands).
Important variables are bill length (mean: 43.92 mm), bill depth (mean:
17.15 mm), and flipper length (mean: 200.9), body mass (mean: 4202 g),
and sex. The data were collected from 2007 - 2009.

Creating a plot of flipper length vs bill length

``` r
ggplot(penguins, aes (x = bill_length_mm, y = flipper_length_mm, color = species)) + geom_point()
```

    ## Warning: Removed 2 rows containing missing values (geom_point).

![](p8105_hw1_sb4328_files/figure-gfm/unnamed-chunk-6-1.png)<!-- -->
